@startuml

class GamesPlatform {
    +ArrayList<Player> ListOfPlayers
    +ShowStatistics()
    +TypeGame()
}
abstract class Game {

    +NumberOfPlayers
    {abstract}Introduction()
    +Resume()
    {abstract}Execute()
    {abstract}AssignRoles()
    +SelectPlayers()
}
class TicTacToe {}
class HangMan {}
abstract class Player {

}
class Bot {}
class Human {}

GamesPlatform *-- "10" Player
GamesPlatform *-- "2" Game

Game <|-- TicTacToe
Game <|-- HangMan
Game o--Player
Player <|-- Bot
Player <|-- Human

@enduml